version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ecommerce_admin
      POSTGRES_PASSWORD: S3cur3P@ssw0rd!2024
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
